# Generated by Django 4.1.3 on 2022-12-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
    ]
